# Generated by Django 6.0.7 on 2026-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='current_salary',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='notice_period',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
