# Generated by Django 6.0.7 on 2026-07-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_jobseeker_current_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('pns', 'Preferred Not to Say')], default='pns', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='current_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='is_open_to_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='notice_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobseeker', to='accounts.skill'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='accounts.appuser'),
        ),
    ]
